export const fieldNameMap: Record<string, string> = { 
  id: 'ID', 
  user_id: '用户ID', 
  sec_uid: 'sec_uid', 
  red_id: '小红书ID', 
  short_user_id: '用户ID', 
  user_unique_id: 'user_unique_id', 
  user_signature: '用户签名', 
  create_time: '发布时间', 
  nickname: '昵称', 
  avatar: '头像', 
  ip_location: '地区', 
  add_ts: '抓取时间', 
  last_modify_ts: '抓取修改时间', 
  note_id: '笔记ID', 
  type: '类型', 
  title: '标题', 
  desc: '描述', 
  aweme_id: '抖音ID', 
  aweme_type: '抖音类型', 
  video_url: '视频链接', 
  time: '发布时间', 
  last_udpdate_time: '更新时间', 
  liked_count: '点赞数', 
  collected_count: '收藏数', 
  comment_count: '总评论', 
  valid_comment_count: '有效评论', 
  share_count: '分享数', 
  image_list: '图片列表', 
  tag_list: '标签', 
  note_url: '笔记链接', 
  aweme_url: '抖音链接', 
  cover_url: '封面链接', 
  video_download_url: '视频下载链接', 
  music_download_url: '音乐下载链接', 
  source_keyword: '来源关键词', 
  xsec_token: 'XSecToken', 
  comment_id: '评论ID', 
  content: '内容', 
  sub_comment_count: '子评论数', 
  parent_comment_id: '父级评论ID', 
  like_count: '点赞数', 
  pictures: '图片列表', 
  videos_count: '视频数', 
  video_id: '视频ID', 
  interaction: '互动数', 
  fans: '粉丝数', 
  follows: '关注数', 
  gender: '性别', 
  phone: '手机号', 
  is_exported: '是否导出', 
} 

export const tableColumnWidth: Record<string, string> = { 
  id: '70px', 
  create_time: '105px', 
  add_ts: '105px', 
  time: '105px', 
  last_modify_ts: '105px', 
  liked_count: '80px', 
  collected_count: '70px', 
  comment_count: '70px', 
  valid_comment_count: '85px', 
  share_count: '70px', 
  interaction: '70px', 
  fans: '80px', 
  follows: '80px', 
  gender: '80px', 
  videos_count: '70px', 
  sub_comment_count: '70px', 
  source_keyword: '100px', 
  phone: '120px', 
  short_user_id: '120px', 
  ip_location: '80px', 
  is_exported: '105px', 
  nickname: '150px', 
} 

export const tableDataKey: Record<string, string[]> = { 
  douyin_video: ['title', 'desc', 'source_keyword', 'liked_count', 'comment_count', 'valid_comment_count', 'share_count', 'collected_count', 'nickname', 'create_time', 'add_ts', 'is_exported'], 
  douyin_comment: ['nickname', 'short_user_id', 'phone', 'content', 'ip_location', 'user_signature', 'create_time', 'add_ts', 'is_exported'], 
  douyin_creator: ['nickname', 'phone', 'gender', 'ip_location', 'desc', 'follows', 'fans', 'interaction', 'videos_count', 'add_ts', 'is_exported'], 
  xhs_video: ['title', 'desc', 'source_keyword', 'liked_count', 'comment_count', 'valid_comment_count', 'share_count', 'collected_count', 'nickname', 'time', 'add_ts', 'is_exported'], 
  xhs_comment: ['nickname', 'red_id', 'phone', 'content', 'ip_location', 'desc', 'create_time', 'add_ts', 'is_exported', 'is_crm'], 
  xhs_creator: ['nickname', 'gender', 'ip_location', 'desc', 'follows', 'fans', 'interaction', 'add_ts', 'is_exported', 'is_crm'], 
} 

export const socialMediaOptions = [ 
  { id: 'douyin', name: '抖音', disabled: false }, 
  // { id: 'xhs', name: '小红书', disabled: false }, 
  // { id: 'weibo', name: '微博', disabled: true }, 
  // { id: 'kuaishou', name: '快手', disabled: true }, 
  // { id: 'bilibili', name: '哔哩哔哩', disabled: true }, 
  // { id: 'tieba', name: '百度贴吧', disabled: true }, 
  // { id: 'zhihu', name: '知乎', disabled: true } 
] 

export const categoryOptions = [ 
  { id: 'comment', name: '评论' }, 
  { id: 'video', name: '视频' }, 
  { id: 'creator', name: '创作者' }, 
] 

export const availableTables = [ 
  { id: 'bilibli_contact_info', name: 'bilibli_contact_info' }, 
  { id: 'bilibli_up_dynamic', name: 'bilibli_up_dynamic' }, 
  { id: 'bilibli_up_info', name: 'bilibli_up_info' }, 
  { id: 'bilibli_video', name: 'bilibli_video' }, 
  { id: 'bilibli_video_comment', name: 'bilibli_video_comment' }, 
  { id: 'douyin_aweme', name: 'douyin_aweme' }, 
  { id: 'douyin_aweme_comment', name: 'douyin_aweme_comment' }, 
  { id: 'dy_creator', name: 'dy_creator' }, 
  { id: 'kuaishou_video', name: 'kuaishou_video' }, 
  { id: 'kuaishou_video_comment', name: 'kuaishou_video_comment' }, 
  { id: 'sqlite_sequence', name: 'sqlite_sequence' }, 
  { id: 'tieba_comment', name: 'tieba_comment' }, 
  { id: 'tieba_creator', name: 'tieba_creator' }, 
  { id: 'tieba_note', name: 'tieba_note' }, 
  { id: 'weibo_creator', name: 'weibo_creator' }, 
  { id: 'weibo_note', name: 'weibo_note' }, 
  { id: 'weibo_note_comment', name: 'weibo_note_comment' }, 
  { id: 'xhs_creator', name: 'xhs_creator' }, 
  { id: 'xhs_note', name: 'xhs_note' }, 
  { id: 'xhs_note_comment', name: 'xhs_note_comment' }, 
  { id: 'zhihu_comment', name: 'zhihu_comment' }, 
  { id: 'zhihu_content', name: 'zhihu_content' }, 
  { id: 'zhihu_creator', name: 'zhihu_creator' }, 
]
